# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dependencyimage.jxwydata.com
spec:
  conversion:
    strategy: None
  group: jxwydata.com
  names:
    kind: DependencyImage
    listKind: DependencyImageList
    plural: dependencyimages
    singular: dependencyimage
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DependencyImage is the Schema for the dependencyimages API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DependencyImageSpec defines the desired state of DependencyImage.
            type: object
            properties:
              images:
                description: a list of images that support thin mode, and obtain dependent pom by parsing thin images
                type: array
                items:
                  type: object
                  properties:
                    repository:
                      description: thin image repository url
                      type: string
                    tag:
                      description: thin image tag
                      type: string
              dependencyImageUrl:
                description: dependency image url,used to generate dependency image and push to private docker repository.
                type: string
              latestDependencyImageUrl:
                description: the latest dependency image is used as a diff image to make a new dependency image
          status:
            description: DependencyImageStatus defines the observed state of DependencyImage
            properties:
              ready:
                description: True if all resources are in a ready state and all work
                  is done.
                type: boolean
            required:
            - ready
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
